# Generated by Django 5.2.8 on 2025-11-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('student_id', models.CharField(max_length=50)),
                ('year_level', models.CharField(max_length=50)),
                ('skill_category', models.CharField(choices=[('ai', 'AI Skills'), ('robotics', 'Robotics/IoT Skills'), ('content', 'Digital Content/Editing'), ('research', 'Research & Writing')], max_length=50)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('hours_per_month', models.IntegerField()),
                ('motivation', models.TextField()),
                ('portfolio_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_core_member', models.BooleanField(default=False)),
            ],
        ),
    ]
