# Generated by Django 5.2.8 on 2025-11-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('general_member', 'General Member'), ('steering_member', 'Steering Member')], default='general_member', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
